version: "3"
services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
  parse:
    container_name: parse
    image: parseplatform/parse-server
    environment:
      PARSE_SERVER_APPLICATION_ID: appId
      PARSE_SERVER_MASTER_KEY: masterKey
      PARSE_SERVER_DATABASE_URI: mongodb://mongo:27017/parse
    ports:
      - 1337:1337
    entrypoint:
      - node
      - ./bin/parse-server
      - --mountGraphQL
      - --mountPlayground
  parse-dashboard:
    container_name: parse-dashboard
    image: parseplatform/parse-dashboard
    environment:
      PARSE_DASHBOARD_APP_ID: appId
      PARSE_DASHBOARD_MASTER_KEY: masterKey
      PARSE_DASHBOARD_SERVER_URL: "http://localhost:1337/parse"
      PARSE_DASHBOARD_GRAPHQL_URL: "http://localhost:1337/graphql"
    ports:
      - 4040:4040
    entrypoint:
      - node
      - Parse-Dashboard/index.js
      - --dev
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - 3001:3000
    volumes:
      - ./docker/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
