version: 2
jobs:
  build:
    docker:
      - image: golang:1.13
      - image: postgres:11-alpine
        environment:
          POSTGRES_PASSWORD: postgres
    steps:
      - checkout
      - run: go get ./...
      - run: go get github.com/golang/mock/mockgen@v1.4.3
      - run: go generate ./...
      - run:
          name: Enforce Go Formatted Code
          # https://circleci.com/blog/enforce-build-standards/
          # https://carsonip.me/posts/go-fmt-and-ci/
          command: |
            output=$(go fmt ./... 2>&1)
            test -z "$output"
      - run: go test ./...
